### ISSUE TITLE
Filter on albums page. 

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#551]
Good day dev. When filtering files by Video/animations/images or otherwise, it would be quite useful if the files can be collated in the albums view in their respective folders minus the filtered media.

I am cognizant that this can be done from the 3 dot menu, however you are only left with a long strip of images etc. to scroll through, which can be tedious at times and confusing to keep track of folders and files as everything is mixed into one long vertical strip. 

Appreciate you're continued dedication to this gem 💎 you have created.

**Comment by DroidFloyd** [comment]
Would like to see also a file size overlay on thumbnails, alot of navigation is currently necessary in order to grasp individual file sizes.

**Comment by deckerst** [comment]
> Would like to see also a file size overlay on thumbnails, alot of navigation is currently necessary in order to grasp individual file sizes.

For albums, the "list" layout shows the sizes.

For items, I'll see and add it on the "list" layout if it makes sense.

**Comment by DroidFloyd** [comment]
List layout only shows the size of the whole album, when inside, not shown for individual files. If file size can be shown on the thumbnail for all views like *location and tag icons* it would be useful for all modes (grid, list and mosaic)

Yes you're suggestion makes alot of sense. Just to reiterate respectfully on my first issue, would I be able to see the albums for example if I were to filter by *Video and see all the folders related to that selection, instead of having to scroll all the videos going down a list with this option?

**Comment by DroidFloyd** [comment]
Oh yes 🙀, that's one way to do it. Guess first issue is resolved. Much respect.

**Comment by DroidFloyd** [comment]
My apologies, back to the first issue. I made a screen recording in hopes this will provide better clarity as to what I was suggesting.

[]()https://drive.google.com/file/d/1t0GK345EFpU4JlWHEz_00H6YLq5-spu1/view?usp=drivesdk

**Comment by deckerst** [comment]
Thanks for the video, this was helpful.

I understand what you want but i don't intend to do it that way.

As for the Stats, i think you missed what i suggested. Here's a video where you can see the flow: https://drive.google.com/file/d/1azSsBMHNnSmFW8jfHVIbC2l4o8klpvjz/view?usp=drivesdk

**Comment by DroidFloyd** [comment]
Glad my video was of some use. 
I completely understand at this time. 
Really appreciate you're energy towards my issue. Even more so than the app, you sir are the real gem. Looking forward to raising more meaningful issues in the future🙏
